### ISSUE TITLE
Changing Step value to 100hz causing CAT errors

### ISSUE THREAD

**Issue by Leesam** [florintanasa/OpenExpertSDR#4]
When changing tuning step value to 100hz i get this error:
`Hamlib: kenwood_safe_transaction: wrong answer; len for cmd IF: expected = 37, got 35`

Issue is only seen with step value of 100hz, all other step values work without issue.

**Comment by florintanasa** [comment]
Yes, I thing this is a problem
Pe 21 mai 2016 03:33, "Leesam" notifications@github.com a scris:

**Comment by florintanasa** [comment]
Check now how work because I found where was mistake.
For me work ok, tested with terminal not with wsjtx or fldigi.

**Comment by Leesam** [comment]
This fixed the issue for me.

I tested with WSJT-X and all step values now work.
