### ISSUE TITLE
Cannot find the build directory

### ISSUE THREAD

**Issue by CryptLabs** [florintanasa/OpenExpertSDR#5]
Hello,

I'm trying to build this:

https://github.com/wd8rde/libExtio_genesis

I cannot find the /build directory.

cd OpenExpertSDR/build
mkdir device
cd device
ln -s /usr/local/lib/libextio_genesis.so libextio_genesis.so

I also have the binary in ExpertSDR directory, can you explain how can I install this library correctly?

I'm on Arch Linux, I have compiled the library.

Regards.

**Comment by florintanasa** [comment]
Hi,
Read on wiki how to install on linux https://github.com/florintanasa/OpenExpertSDR/wiki

**Comment by CryptLabs** [comment]
Hello i did follow the steps from the wiki.
I'm getting this on the console while the program is running:

LoadConfigFile:284 Failed to open /home/user/.genesis-sdr.ini for reading

**Comment by CryptLabs** [comment]
I'm getting this error box when starting ExpertSDR:

Init hardware failed.

**Comment by florintanasa** [comment]
This error exist because you not have G11 or G59 connected and power on or if is connected and power on you not have wright to read/send command on SDR G11 or G59.
In arch linux try to change in the rules from group plugdev to uucp and you user to be member in this group.

**Comment by CryptLabs** [comment]
What do you mean by change the rules from group plugdev to uucp ?

I have added the user to uucp.

**Comment by CryptLabs** [comment]
I'm getting this when I try to start ExpertSDR:

LoadConfigFile:284 Failed to open /home/al1nux/.genesis-sdr.ini for reading

**Comment by CryptLabs** [comment]
This is all the log i get:

qApp: set translation file - file is not exist!
QObject::connect: No such signal QextSerialPort::ctsChanged(bool)
QObject::connect:  (receiver name: 'OptionsClass')
QObject::connect: No such signal QextSerialPort::ctsChanged(bool)
QObject::connect:  (receiver name: 'OptionsClass')
QObject::connect: No such signal QextSerialPort::ctsChanged(bool)
QObject::connect:  (receiver name: 'OptionsClass')
libpng warning: iCCP: known incorrect sRGB profile
QObject::connect: No such signal QextSerialPort::ctsChanged(bool)
QObject::connect: No such slot fileList::onBack()
QObject::connect:  (sender name:   'pbBack')
QObject::connect:  (receiver name: 'fileListClass')
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ExpertSDR_vA2_1 : 1152  MicScale= 0.142857  MicGainScale= 1
ExpertSDR: readSettings()
ExpertSDR: readSettings(): LevelOutVoltage =  2.2
OnMic : 5084  MicScale= 0.328571  MicGainScale= 1
OnMic : 5084  MicScale= 0.328571  MicGainScale= 1
SetPreamp : 130  Preamp: 0
ExpertSDR: readSettings(): Band60: BandFreq =  27149
InitHW:138
Init:53  vid:fffe, pid:1970
Init:62 Error vid:fffe, pid:1970 not found
LoadConfigFile:284 Failed to open /home/al1nux/.genesis-sdr.ini for reading
private_cmd_arg2only:395 Error device is NULL
private_cmd_arg2only:395 Error device is NULL
private_cmd_arg2only:395 Error device is NULL
private_cmd_arg2only:395 Error device is NULL
private_cmd_arg2only:395 Error device is NULL
Init:53  vid:fffe, pid:1971
Init:62 Error vid:fffe, pid:1971 not found
LoadConfigFile:284 Failed to open /home/al1nux/.genesis-sdr.ini for reading
private_cmd_arg2only:395 Error device is NULL
private_cmd_arg2only:395 Error device is NULL
private_cmd_arg2only:395 Error device is NULL
private_cmd_arg2only:395 Error device is NULL
private_cmd_arg2only:395 Error device is NULL
SetRx1Osc is set: -3149
ExpertSDR: OnChangeBand(  13  )
ExpertSDR: OnChangeMode(  1  )
SetPreamp : 130  Preamp: 0
RX1_CHANNEL is set: 1
RX2_CHANNEL is set: 1
SetCallback:245
ExpertSDR: OnChangeBand(  13  )
ExpertSDR: OnChangeMode(  1  )
SetPreamp : 130  Preamp: 0
RX1_CHANNEL is set: 1
RX2_CHANNEL is set: 1
ExpertSDR: OnStart(false).
SetRx1Osc is set: 0
ExpertSDR: OnChangeBand(  0  )
ExpertSDR: OnChangeMode(  1  )
SetPreamp : 130  Preamp: 0
RX1_CHANNEL is set: 1
RX2_CHANNEL is set: 1
ExpertSDR: writeSettings()
CwMacro: writeSettings()
Panarama: writeSettings()

**Comment by florintanasa** [comment]
First of all what SDR you have G11 or G59 because in log I saw
Init:62 Error vid:fffe, pid:1970 not found
and
Init:62 Error vid:fffe, pid:1971 not found
In wiki I wrote

> To let regular user to have acces at usb G59/G11 board is necessary to add rules in udev
Now we create a file named 26-xSDR.rules with your favorite editor (nano or mousepad or gedit) in /etc/udev/rules.d

>`sudo nano -w /etc/udev/rules.d/26-xSDR.rules`

>#and we add this lines

>#xSDR – rules for G11 SDR
SUBSYSTEMS=="usb", ATTRS{idVendor}=="fffe", ATTRS{idProduct}=="1971", GROUP="plugdev", MODE="0660"
#xSDR – rules for G59 SDR
SUBSYSTEMS=="usb", ATTRS{idVendor}=="fffe", ATTRS{idProduct}=="1970", GROUP="plugdev", MODE="0660"

>#after we save and close the file the users from group plugdev have access to write/read from device G59 or G11 but to load new modification for new users in linux is better to reboot in this moment

So for arch linux change word plugdev with uucp and add user to this grup
`sudo gpasswd -a $(whoami) uucp`

I think you understood that, your user not have wright to access the device (SDR) if this is connected to computers and is on.

**Comment by CryptLabs** [comment]
I have the G59.

OK, I will try to create the rules and add the user.

Hope it works.

Thanks for your great support :)

**Comment by CryptLabs** [comment]
OK, it's working now.

However, I'm getting a clicking sound every time this gets incremented:

@@@ mon [4924]: cb = 0 rbi = 1 rbo = 1 xr = 0
@@@ mon [4925]: cb = 0 rbi = 1 rbo = 1 xr = 0
@@@ mon [5017]: cb = 0 rbi = 1 rbo = 1 xr = 0
@@@ mon [5039]: cb = 0 rbi = 1 rbo = 1 xr = 0
@@@ mon [5146]: cb = 0 rbi = 1 rbo = 1 xr = 0

**Comment by florintanasa** [comment]
Great news.
I know clicking sound when you change the frequency.
At the end at the file expertsdr_va2_1.cpp I put some shortcut keys to some commands, look in file.
For example with key UP and DOWN we change the frequency with key LEFT and RIGHT we change the step frequency and with key PAGE_UP and PAGE_DOWN we move the filter.
When you move the filter you not have clicking sound.

**Comment by CryptLabs** [comment]
The clicking sound also while listening to a station.

When i change buffer size it changes also, somw times fast clicking band
sometimes slow.
